title: Ajay Ragh
description: A simple portfolio and blog
author: Ajay Ragh
url: "https://username.github.io"
theme: jekyll-theme-cayman

collections:
  novels:
    output: true
    files: "*.md"
    fields:
      - title
      - chapter_number
      - chapters:
        fields:
          - title
          - chapter_number