title: Ajay Ragh
description: A simple portfolio and blog
author: Ajay Ragh
url: "https://username.github.io"
theme: jekyll-theme-cayman

collections:
  novels:
    output: true
    files: "*.md"  # This tells Jekyll to process all markdown files within the novels directory
    fields:  # This defines the keys Jekyll will extract from each markdown file
      - title  # This expects each novel markdown file to have a "title" key
      - chapters:  # This expects a nested key named "chapters" containing details about chapters.
        fields:  # This defines nested fields for chapter details within each novel
          - title  # Each chapter object should have a "title" key
          # ... other chapter fields like number, content, etc. ...